#ifndef __NET_CONSTANTS__
typedef enum
{
	NET_ERROR_PACKET=0,
	NET_STATUS_PACKET=1,
	NET_ULTRASONIC_MESSAGE_PACKET=2,
	NET_COMMAND_PACKET=3,
	NET_COLOR_MESSAGE_PACKET=4,
	NET_BUZZER_PACKET=5,
	NET_MESSAGE_PACKET=6,	// for debugging
	NET_MANUALMODE_PACKET=7,
} TNetConstants;

#endif
